<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="content" nsURI="http:///de/otpiccolo/dsa5/model/pdf/content.ecore"
    nsPrefix="de.otpiccolo.dsa5.model.pdf.content">
  <eClassifiers xsi:type="ecore:EClass" name="DataContent" eSuperTypes="#//PageContent">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="content" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="contentType" eType="#//ContentType"
        unsettable="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PageContent" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="ParagraphContent" eSuperTypes="#//PageContent">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="paragraphs" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ImageContent" eSuperTypes="#//PageContent">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="imageFile" eType="#//File"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TableCell">
    <eStructuralFeatures xsi:type="ecore:EReference" name="row" eType="#//TableRow"
        transient="true" eOpposite="#//TableRow/cells"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="content" eType="#//PageContent"
        containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TableContent" eSuperTypes="#//PageContent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="rows" upperBound="-1" eType="#//TableRow"
        containment="true" resolveProxies="false" eOpposite="#//TableRow/table"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="columnCount" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="columnWeights" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TableRow">
    <eStructuralFeatures xsi:type="ecore:EReference" name="table" eType="#//TableContent"
        transient="true" eOpposite="#//TableContent/rows"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cells" upperBound="-1"
        eType="#//TableCell" containment="true" resolveProxies="false" eOpposite="#//TableCell/row"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ContentType">
    <eLiterals name="AllgemeineSonderfertigkeit" literal="Allgemeine Sonderfertigkeit"/>
    <eLiterals name="BannSchutzKreis" value="1" literal="Bann-/Schutzkreis"/>
    <eLiterals name="Elfenlied" value="2" literal="Elfenlied"/>
    <eLiterals name="Elixier" value="3" literal="Elixier"/>
    <eLiterals name="ErweiterterLiturgiestil" value="4" literal="Erweiterter Liturgiestil"/>
    <eLiterals name="ErweiterterTalentstil" value="5" literal="Erweiterter Talentstil"/>
    <eLiterals name="Gewandzauber" value="6" literal="Gewandzauber"/>
    <eLiterals name="Hexenfluch" value="7" literal="Hexenfluch"/>
    <eLiterals name="Kampfsonderfertigkeit" value="8" literal="Kampf-Sonderfertigkeit"/>
    <eLiterals name="Kampfstilsonderfertigkeit" value="9" literal="Kampfstil-Sonderfertigkeit"/>
    <eLiterals name="KarmaleSonderfertigkeit" value="10" literal="Karmale Sonderfertigkeit"/>
    <eLiterals name="KarmaleTradition" value="11" literal="Karmale Tradition"/>
    <eLiterals name="Liturgie" value="12" literal="Liturgie"/>
    <eLiterals name="Liturgiestil" value="13"/>
    <eLiterals name="MagischeSonderfertigkeit" value="14" literal="Magische Sonderfertigkeit"/>
    <eLiterals name="Nachteil" value="15" literal="Nachteil"/>
    <eLiterals name="Predigt" value="16" literal="Predigt"/>
    <eLiterals name="Ritual" value="17" literal="Ritual"/>
    <eLiterals name="SchicksalspunktSonderfertigkeit" value="18" literal="Schicksalspunkt-Sonderfertigkeit"/>
    <eLiterals name="Segen" value="19" literal="Segen"/>
    <eLiterals name="TalentstilSonderfertigkeit" value="20" literal="Talentstil-Sonderfertigkeit"/>
    <eLiterals name="Vision" value="21" literal="Vision"/>
    <eLiterals name="Vorteil" value="22" literal="Vorteil"/>
    <eLiterals name="Zauber" value="23" literal="Zauber"/>
    <eLiterals name="Zaubererweiterung" value="24" literal="Zaubererweiterung"/>
    <eLiterals name="Zauberstil" value="25" literal="Zauberstil"/>
    <eLiterals name="Zaubertanz" value="26" literal="Zaubertanz"/>
    <eLiterals name="ZauberTradition" value="27" literal="Zauber-Tradition"/>
    <eLiterals name="Zaubertrick" value="28" literal="Zaubertrick"/>
    <eLiterals name="Zeremonialgegenstand" value="29" literal="Zeremonialer Gegenstand"/>
    <eLiterals name="Zeremonie" value="30" literal="Zeremonie"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="File" instanceClassName="java.io.File"/>
</ecore:EPackage>
