<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="content" nsURI="http:///de/otpiccolo/dsa5/model/pdf/content.ecore"
    nsPrefix="de.otpiccolo.dsa5.model.pdf.content">
  <eClassifiers xsi:type="ecore:EClass" name="DataContent" eSuperTypes="#//PageContent">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="content" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="contentType" eType="#//ContentType"
        unsettable="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PageContent" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="ParagraphContent" eSuperTypes="#//PageContent">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="paragraphs" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ImageContent" eSuperTypes="#//PageContent">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="imagePath" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TableCell">
    <eStructuralFeatures xsi:type="ecore:EReference" name="row" eType="#//TableRow"
        transient="true" eOpposite="#//TableRow/cells"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="content" eType="#//PageContent"
        containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TableContent" eSuperTypes="#//PageContent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="rows" upperBound="-1" eType="#//TableRow"
        containment="true" resolveProxies="false" eOpposite="#//TableRow/table"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="columnCount" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="columnWeights" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TableRow">
    <eStructuralFeatures xsi:type="ecore:EReference" name="table" eType="#//TableContent"
        transient="true" eOpposite="#//TableContent/rows"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cells" upperBound="-1"
        eType="#//TableCell" containment="true" resolveProxies="false" eOpposite="#//TableCell/row"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ContentType">
    <eLiterals name="AllgemeineSonderfertigkeit"/>
    <eLiterals name="Elfenlied" value="1"/>
    <eLiterals name="Elixier" value="2"/>
    <eLiterals name="ErweiterterLiturgiestil" value="3"/>
    <eLiterals name="Hexenfluch" value="4"/>
    <eLiterals name="KarmaleSonderfertigkeit" value="5"/>
    <eLiterals name="KarmaleTradition" value="6"/>
    <eLiterals name="Kampfsonderfertigkeit" value="7"/>
    <eLiterals name="Kampfstilsonderfertigkeit" value="8"/>
    <eLiterals name="Liturgie" value="9"/>
    <eLiterals name="Liturgiestil" value="10"/>
    <eLiterals name="Nachteil" value="11"/>
    <eLiterals name="Predigt" value="12"/>
    <eLiterals name="Segen" value="13"/>
    <eLiterals name="Vision" value="14"/>
    <eLiterals name="Vorteil" value="15"/>
    <eLiterals name="Zauber" value="16"/>
    <eLiterals name="Zaubererweiterung" value="17"/>
    <eLiterals name="Zauberstil" value="18"/>
    <eLiterals name="Zaubertanz" value="19"/>
    <eLiterals name="ZauberTradition" value="20"/>
    <eLiterals name="Zaubertrick" value="21"/>
    <eLiterals name="Zeremonialgegenstand" value="22"/>
    <eLiterals name="Zeremonie" value="23"/>
  </eClassifiers>
</ecore:EPackage>
