<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="page" nsURI="http:///de/otpiccolo/dsa5/model/pdf/page.ecore"
    nsPrefix="de.otpiccolo.dsa5.model.pdf.page">
  <eClassifiers xsi:type="ecore:EClass" name="DefaultPage" eSuperTypes="#//Page">
    <eStructuralFeatures xsi:type="ecore:EReference" name="contents" upperBound="-1"
        eType="ecore:EClass content.ecore#//PageContent" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Page" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="PdfPage" eSuperTypes="#//Page">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="file" eType="#//File"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pageNumbers" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PredefinedPage" eSuperTypes="#//Page">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="#//PredefinedType"
        unsettable="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="PredefinedType">
    <eLiterals name="Boron"/>
    <eLiterals name="Efferd" value="1"/>
    <eLiterals name="EntrueckungTrance" value="2"/>
    <eLiterals name="FernkampfMod" value="3"/>
    <eLiterals name="Firun" value="4"/>
    <eLiterals name="Hesinde" value="5"/>
    <eLiterals name="Ingerimm" value="6"/>
    <eLiterals name="Peraine" value="7"/>
    <eLiterals name="Phex" value="8"/>
    <eLiterals name="Praios" value="9"/>
    <eLiterals name="Rahja" value="10"/>
    <eLiterals name="Reiterkampf" value="11"/>
    <eLiterals name="Rondra" value="12"/>
    <eLiterals name="Schicksalspunkte" value="13"/>
    <eLiterals name="Segen" value="14"/>
    <eLiterals name="Travia" value="15"/>
    <eLiterals name="Tsa" value="16"/>
    <eLiterals name="ZauberMod" value="17"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Collection" instanceClassName="java.util.Collection">
    <eTypeParameters name="T"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="File" instanceClassName="java.io.File"/>
</ecore:EPackage>
